function run(){
			var bo = '<b style=display:block;>';
			var ld = '</b>';
			var ft = '<title>';
			var lt = '</title>';
			var fi = '<i>';
			var li = '</i>';
			var p1 = '<p>';
			var p2 = '</p>';
			var ha = '<h1>';
			var hb = '</h1>';
			var hc = '<h2>';
			var hd = '</h2>';
			var he = '<h3>';
			var hf = '</h3>';
			var hg = '<h4>';
			var hh = '</h4>';
			var hi = '<h5>';
			var hj = '</h5>';
			var hk = '<h6>';
			var hl = '</h6>';
			var selectnone = '<style>:root{user-select:none;}</style>';
			var center = '<style>:root{position: absolute;text-align: center;left: 50%;top: 50%;transform: translate(-50%, -50%);}</style>';
			var time = new Date();
			var help = 'Jvav NoSoft DSK 1+ 语法帮助:<br/>原Jvav DSK 6+语法:<br/>help:获取语法帮助<br/>time:获取当前时间<br/>bo + ld:加粗字体<br/>fi + li:倾斜字体<br/>ft + lt:设置程序标题<br/>selectnone/sn:设置程序不可选中普通文本<br/>center/middle:将显示位置绝对居中(垂直+水平)<br/>新Jvav NoSoft DSK 1+语法:<br/>p1 + p2:原HTML P 标签<br/>提示:语法带+指闭合语法,前后者顺序分明,如:<br/>bo 你好 ld:<b> 你好 </b><br/><a href=\'https://vdse.bdstatic.com/192d9a98d782d9c74c96f09db9378d93.mp4\' target=\'_blank\'>点此查看详细文档</a>'
			var acode = code.replace(/time/g,time);
			var bcode = acode.replace(/ld/g,ld);
			var ccode = bcode.replace(/bo/g,bo);
			var dcode = ccode.replace(/ft/g,ft);
			var ecode = dcode.replace(/selectnone|sn/g,selectnone);
			var fcode = ecode.replace(/center|middle/g,center);
			var gcode = fcode.replace(/fi/g,fi);
			var hcode = gcode.replace(/li/g,li);
			var icode = hcode.replace(/p1/g,p1);
			var jcode = icode.replace(/p2/g,p2);
			var h1code = jcode.replace(/ha/g,ha);
			var h1hcode = h1code.replace(/hb/g,hb);
			var h2code = h1hcode.replace(/hc/g,hc);
			var h2hcode = h2code.replace(/hd/g,hd);
			var h3code = h2hcode.replace(/he/g,he);
			var h3hcode = h3code.replace(/hf/g,hf);
			var h4code = h3hcode.replace(/hg/g,hg);
			var h4hcode = h4code.replace(/hh/g,hh);
			var h5code = h4hcode.replace(/hi/g,hi);
			var h5hcode = h5code.replace(/hj/g,hj);
			var h6code = h5hcode.replace(/hk/g,hk);
			var h6hcode = h6code.replace(/hl/g,hl);
			var lastcode = h6hcode.replace(/lt/g,lt);
			var finalcode = lastcode.replace(/help/g,help);
			window.open().document.write(finalcode);
		}